### PR TITLE
Bugfix/parameter file reference

### LINKED ISSUE #33: Pipeline parameters invalid file references
## Description
In Azure and GitHub, when we load Parameters for inputs (GitHub Actions/ Azure Tasks), the file references are loaded dynamically according to the order of the map, which is different in runtime.

## What did you expect to happen?
The file references should be correct to the location in the file itself.

## What happened instead?
The lines were wrong

### PR DESCRIPTION
**Pull request by orizerah**
## Description
This pull request introduces a common model called `Map` which is a map of key values.
The Map is loaded as a YAML Unmarshaller and therefor the file references are correct.
This pull request also uses `Map` in relevant locations. 

## Related issues
- Close #33 

## Checklist
- [x] I've read the [guidelines for contributing](https://github.com/argonsecurity/pipeline-parser/blob/main/CONTRIBUTING.md) to this repository.
- [x] I've followed the [conventions](https://github.com/argonsecurity/pipeline-parser/blob/main/CONTRIBUTING.md#pull-requests) in the PR title.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [x] I've updated the [readme](https://github.com/argonsecurity/pipeline-parser/blob/main/README.md) with the relevant information (if needed).

### CODE REVIEW

File: pkg/loaders/github/models/step.go [hunk 1]
```diff
@@ -28,7 +26,7 @@ type Step struct {
 	Shell            string                   `yaml:"shell,omitempty"`
 	TimeoutMinutes   int                      `yaml:"timeout-minutes,omitempty"`
 	Uses             string                   `yaml:"uses,omitempty"`
-	With             *With                    `yaml:"with,omitempty"`
+	With             With                     `yaml:"with,omitempty"`
```
Comment (tamirkiviti13) [inline pkg/loaders/github/models/step.go:29]:
```suggestion
	With             *commonModels.Map                     `yaml:"with,omitempty"`
```

File: pkg/parsers/azure/steps_test.go [hunk 2]
```diff
@@ -522,47 +534,58 @@ func TestParseActionHeader(t *testing.T) {
...
+					FileReference: testutils.CreateFileReference(114, 224, 114, 234),
+				},
+			},
+		},
 	}
 
 	for _, testCase := range testCases {
 		t.Run(testCase.name, func(t *testing.T) {
-			got := parseTaskInput(testCase.taskInputs)
+			got := parserUtils.ParseMapToParameters(testCase.taskInputs)
```
Comment (tamirkiviti13) [inline pkg/parsers/azure/steps_test.go:588]: This test belongs to utils package and not here

File: pkg/parsers/github/steps_test.go [hunk 3]
```diff
@@ -355,47 +369,59 @@ func TestParseActionHeader(t *testing.T) {
...
+					FileReference: testutils.CreateFileReference(114, 224, 114, 234),
+				},
+			},
+		},
 	}
 
 	for _, testCase := range testCases {
 		t.Run(testCase.name, func(t *testing.T) {
-			got := parseActionInput(testCase.with)
+			got := parserUtils.ParseMapToParameters(testCase.with)
```
Comment (tamirkiviti13) [inline pkg/parsers/github/steps_test.go:424]: This test doesn't belong here

**Review by tamirkiviti13 — APPROVED** [review]
